server:
  port: 8087
spring:
  application:
    name: eCommerce
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: Nm47ys97n02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    allow-circular-references: true
